import type { RuntimeEvent } from '../engine/runtime-events';

export const demoEventScripts: Record<string, RuntimeEvent[]> = {
  'array-index-of': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'MOVE_POINTER', name: 'i', index: 1 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 1, value: 2 },
    { type: 'COMPARE', left: 2, operator: '==', right: 2, result: true },
    { type: 'LINE_ENTER', line: 7 },
    { type: 'SET_VAR', name: 'answer', value: 1 },
    { type: 'FINISH' },
  ],
  'array-last-index-of': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'MOVE_POINTER', name: 'i', index: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 5, value: 2 },
    { type: 'COMPARE', left: 2, operator: '==', right: 2, result: true },
    { type: 'LINE_ENTER', line: 7 },
    { type: 'SET_VAR', name: 'answer', value: 5 },
    { type: 'FINISH' },
  ],
  'array-contains': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 3, value: 2 },
    { type: 'COMPARE', left: 2, operator: '==', right: 8, result: false },
    { type: 'MOVE_POINTER', name: 'i', index: 4 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 6, value: 7 },
    { type: 'COMPARE', left: 7, operator: '==', right: 8, result: false },
    { type: 'FINISH' },
  ],
  'array-binary-search': [
    { type: 'LINE_ENTER', line: 10 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 3, value: 7 },
    { type: 'COMPARE', left: 7, operator: '==', right: 9, result: false },
    { type: 'COMPARE', left: 7, operator: '<', right: 9, result: true },
    { type: 'MOVE_POINTER', name: 'left', index: 4 },
    { type: 'MOVE_POINTER', name: 'mid', index: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 5, value: 11 },
    { type: 'COMPARE', left: 11, operator: '>', right: 9, result: true },
    { type: 'MOVE_POINTER', name: 'right', index: 4 },
    { type: 'MOVE_POINTER', name: 'mid', index: 4 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 4, value: 9 },
    { type: 'COMPARE', left: 9, operator: '==', right: 9, result: true },
    { type: 'SET_VAR', name: 'answer', value: 4 },
    { type: 'FINISH' },
  ],
  'array-find-max': [
    { type: 'LINE_ENTER', line: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 1, value: 8 },
    { type: 'COMPARE', left: 8, operator: '>', right: 3, result: true },
    { type: 'SET_VAR', name: 'max', value: 8 },
    { type: 'MOVE_POINTER', name: 'i', index: 2 },
    { type: 'FINISH' },
  ],
  'array-find-min': [
    { type: 'LINE_ENTER', line: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 2, value: 1 },
    { type: 'COMPARE', left: 1, operator: '<', right: 3, result: true },
    { type: 'SET_VAR', name: 'min', value: 1 },
    { type: 'MOVE_POINTER', name: 'i', index: 3 },
    { type: 'FINISH' },
  ],
  'array-index-of-max': [
    { type: 'LINE_ENTER', line: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 4, value: 9 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 1, value: 8 },
    { type: 'COMPARE', left: 9, operator: '>', right: 8, result: true },
    { type: 'SET_VAR', name: 'maxIndex', value: 4 },
    { type: 'MOVE_POINTER', name: 'i', index: 5 },
    { type: 'FINISH' },
  ],
  'array-index-of-min': [
    { type: 'LINE_ENTER', line: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 2, value: 1 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 0, value: 3 },
    { type: 'COMPARE', left: 1, operator: '<', right: 3, result: true },
    { type: 'SET_VAR', name: 'minIndex', value: 2 },
    { type: 'MOVE_POINTER', name: 'i', index: 3 },
    { type: 'FINISH' },
  ],
  'array-sum-elements': [
    { type: 'LINE_ENTER', line: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 0, value: 3 },
    { type: 'SET_VAR', name: 'sum', value: 3 },
    { type: 'MOVE_POINTER', name: 'i', index: 1 },
    { type: 'LINE_ENTER', line: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 5, value: 2 },
    { type: 'SET_VAR', name: 'sum', value: 29 },
    { type: 'FINISH' },
  ],
  'array-average-elements': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 5, value: 2 },
    { type: 'SET_VAR', name: 'sum', value: 29 },
    { type: 'MOVE_POINTER', name: 'i', index: 6 },
    { type: 'LINE_ENTER', line: 10 },
    { type: 'SET_VAR', name: 'average', value: 4.833333333333333 },
    { type: 'FINISH' },
  ],
  'array-count-occurrences': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 0, value: 2 },
    { type: 'COMPARE', left: 2, operator: '==', right: 2, result: true },
    { type: 'SET_VAR', name: 'count', value: 1 },
    { type: 'MOVE_POINTER', name: 'i', index: 1 },
    { type: 'FINISH' },
  ],
  'array-reverse': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'SWAP', arrayName: 'arr', i: 0, j: 4 },
    { type: 'MOVE_POINTER', name: 'i', index: 1 },
    { type: 'MOVE_POINTER', name: 'j', index: 3 },
    { type: 'FINISH' },
  ],
  'array-bubble-sort': [
    { type: 'LINE_ENTER', line: 6 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 0, value: 5 },
    { type: 'READ_ARRAY', arrayName: 'arr', index: 1, value: 1 },
    { type: 'COMPARE', left: 5, operator: '>', right: 1, result: true },
    { type: 'SWAP', arrayName: 'arr', i: 0, j: 1 },
    { type: 'MOVE_POINTER', name: 'j', index: 1 },
    { type: 'FINISH' },
  ],
};